#!/usr/bin/env bash
# RaVN webapp launchers — uses local icons from ~/.local/share/applications/icons/
# Re-run via: bash ~/Work/RaVN/dev/Scripts/launchers/install_launchers.sh

ravn_webapp_install 'Basecamp' 'https://launchpad.37signals.com' 'Basecamp.png'
ravn_webapp_install 'Canva ai' 'https://www.canva.com/?success=true&continue_in_browser=true' 'Canva ai.png'
ravn_webapp_install 'ChatGPT' 'https://chatgpt.com/' 'ChatGPT.png'
ravn_webapp_install 'ChatGPT Codex Cloud' 'https://chatgpt.com/codex/cloud' 'ChatGPT.png'
ravn_webapp_install 'Claro Video' 'https://www.clarovideo.com/elsalvador/homeuser' 'Claro Video.png'
ravn_webapp_install 'Claude AI' 'https://claude.ai/new' 'Claude AI.png'
ravn_webapp_install 'Deepseek ai' 'https://chat.deepseek.com/' 'Deepseek ai.png'
ravn_webapp_install 'Discord' 'https://discord.com/channels/@me' 'Discord.png'
ravn_webapp_install 'Disney' 'https://www.disneyplus.com/es-sv' 'Disney.png'
ravn_webapp_install 'ExcaliDraw' 'https://excalidraw.com/' 'ExcaliDraw.png'
ravn_webapp_install 'Figma' 'https://figma.com/' 'Figma.png'
ravn_webapp_install 'Fizzy' 'https://app.fizzy.do/' 'Fizzy.png'
ravn_webapp_install 'Fronted Masters' 'https://frontendmasters.com/dashboard/' 'Fronted Masters.png'
ravn_webapp_install 'Gemini AI' 'https://gemini.google.com/app' 'Gemini AI.png'
ravn_webapp_install 'GitHub' 'https://github.com/' 'GitHub.png'
ravn_webapp_install 'Gitkraken dev' 'https://gitkraken.dev/launchpad/personal?prs=github&issues=github' 'Gitkraken dev.png'
ravn_webapp_install 'Go Rails' 'https://gorails.com/' 'Go Rails.png'
ravn_webapp_install 'Google Contacts' 'https://contacts.google.com/' 'Google Contacts.png'
ravn_webapp_install 'Google Maps' 'https://maps.google.com' 'Google Maps.png'
ravn_webapp_install 'Google Messages' 'https://messages.google.com/web/conversations' 'Google Messages.png'
ravn_webapp_install 'Google Photos' 'https://photos.google.com/' 'Google Photos.png'
ravn_webapp_install 'Grok AI' 'https://grok.com/' 'Grok AI.png'
ravn_webapp_install 'HBO' 'https://play.hbomax.com/' 'HBO.png'
ravn_webapp_install 'HEY' 'https://app.hey.com' 'HEY.png' 'omarchy-webapp-handler-hey %u' 'x-scheme-handler/mailto'
ravn_webapp_install 'Kimi ai' 'https://www.kimi.com/' 'Kimi ai.png'
ravn_webapp_install 'M365 Copilot ai' 'https://m365.cloud.microsoft/chat/' 'M365 Copilot ai.png'
ravn_webapp_install 'Manus ai' 'https://manus.im/app' 'Manus ai.png'
ravn_webapp_install 'MiMo AI Studio' 'https://aistudio.xiaomimimo.com/#/c' 'mimo.png'
ravn_webapp_install 'Mistral ai' 'https://chat.mistral.ai/chat' 'Mistral ai.png'
ravn_webapp_install 'minimax Agent' 'https://agent.minimax.io/' 'minimax.png'
ravn_webapp_install 'Monica HQ' 'https://www.monicahq.com/' 'monica-hq.png'
ravn_webapp_install 'Netflix' 'https://www.netflix.com/browse' 'Netflix.png'
ravn_webapp_install 'NotebookLM' 'https://notebooklm.google.com/' 'NotebookLM.png'
ravn_webapp_install 'Notion ' 'https://www.notion.so/OMARCHY-28ae971e6e8b8025b230ec19f39596e7?showMoveTo=true&saveParent=true' 'Notion .png'
ravn_webapp_install 'OpenClaw Dashboard' 'http://127.0.0.1:18789' 'OpenClaw.png'
ravn_webapp_install 'Perplexity ai' 'https://www.perplexity.ai/' 'Perplexity ai.png'
ravn_webapp_install 'Raindrop' 'https://app.raindrop.io/my/0' 'Raindrop.png'
ravn_webapp_install 'Platzi' 'https://platzi.com/home/' 'Platzi.png'
ravn_webapp_install 'Qwen Coder' 'https://coder.qwen.ai/' 'Qwen ai.png'
ravn_webapp_install 'Qwen ai' 'https://chat.qwen.ai/' 'Qwen ai.png'
ravn_webapp_install 'TickTick' 'https://ticktick.com/' 'TickTick.svg'
ravn_webapp_install 'Tigo Sports' 'https://www.tigosports.com.sv/inicio' 'Tigo Sports.png'
ravn_webapp_install 'Vix' 'https://vix.com/es-es' 'Vix.png'
ravn_webapp_install 'WhatsApp' 'https://web.whatsapp.com/' 'WhatsApp.png'
ravn_webapp_install 'X' 'https://x.com/' 'X.png'
ravn_webapp_install 'XB' 'https://x.com/i/bookmarks' 'X.png'
ravn_webapp_install 'XG' 'https://x.com/i/grok' 'X.png'
ravn_webapp_install 'YouTube' 'https://youtube.com/' 'YouTube.png'
ravn_webapp_install 'Z' 'https://chat.z.ai/' 'Z.png'
ravn_webapp_install 'Zoom' 'https://app.zoom.us/wc/home' 'Zoom.png' 'omarchy-webapp-handler-zoom %u' 'x-scheme-handler/zoommtg;x-scheme-handler/zoomus'
